// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhkcyuhrjmuqqlmyczwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oa2N5dWhyam11cXFsbXljendqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzc0NzUsImV4cCI6MjA2MzkxMzQ3NX0.WU53SFSGpTE7t9naKHlIlnKAtBtP4Ax42oanZKOPrN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);